version: '3'

services:
  python-app:
    container_name: python_app
    build: 
      context: .
      dockerfile: dockerfile

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - python-app
    container_name: ofelia
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.ini:/etc/ofelia/config.ini